// Code generated by protoc-gen-go. DO NOT EDIT.
// source: syncer.proto

package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto2 "github.com/apache/servicecomb-service-center/server/core/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PullRequest struct {
	ServiceName string `protobuf:"bytes,1,opt,name=serviceName" json:"serviceName,omitempty"`
	Options     string `protobuf:"bytes,2,opt,name=options" json:"options,omitempty"`
	Time        string `protobuf:"bytes,3,opt,name=time" json:"time,omitempty"`
}

func (m *PullRequest) Reset()                    { *m = PullRequest{} }
func (m *PullRequest) String() string            { return proto1.CompactTextString(m) }
func (*PullRequest) ProtoMessage()               {}
func (*PullRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *PullRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *PullRequest) GetOptions() string {
	if m != nil {
		return m.Options
	}
	return ""
}

func (m *PullRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type SyncService struct {
	DomainProject string                         `protobuf:"bytes,1,opt,name=domainProject" json:"domainProject,omitempty"`
	Service       *proto2.MicroService           `protobuf:"bytes,2,opt,name=service" json:"service,omitempty"`
	Instances     []*proto2.MicroServiceInstance `protobuf:"bytes,3,rep,name=instances" json:"instances,omitempty"`
}

func (m *SyncService) Reset()                    { *m = SyncService{} }
func (m *SyncService) String() string            { return proto1.CompactTextString(m) }
func (*SyncService) ProtoMessage()               {}
func (*SyncService) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *SyncService) GetDomainProject() string {
	if m != nil {
		return m.DomainProject
	}
	return ""
}

func (m *SyncService) GetService() *proto2.MicroService {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *SyncService) GetInstances() []*proto2.MicroServiceInstance {
	if m != nil {
		return m.Instances
	}
	return nil
}

type SyncData struct {
	Services []*SyncService `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *SyncData) Reset()                    { *m = SyncData{} }
func (m *SyncData) String() string            { return proto1.CompactTextString(m) }
func (*SyncData) ProtoMessage()               {}
func (*SyncData) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *SyncData) GetServices() []*SyncService {
	if m != nil {
		return m.Services
	}
	return nil
}

type SyncMapping struct {
	DomainProject string `protobuf:"bytes,1,opt,name=domainProject" json:"domainProject,omitempty"`
	OrgServiceID  string `protobuf:"bytes,2,opt,name=orgServiceID" json:"orgServiceID,omitempty"`
	OrgInstanceID string `protobuf:"bytes,3,opt,name=OrgInstanceID" json:"OrgInstanceID,omitempty"`
	CurServiceID  string `protobuf:"bytes,4,opt,name=CurServiceID" json:"CurServiceID,omitempty"`
	CurInstanceID string `protobuf:"bytes,5,opt,name=CurInstanceID" json:"CurInstanceID,omitempty"`
}

func (m *SyncMapping) Reset()                    { *m = SyncMapping{} }
func (m *SyncMapping) String() string            { return proto1.CompactTextString(m) }
func (*SyncMapping) ProtoMessage()               {}
func (*SyncMapping) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *SyncMapping) GetDomainProject() string {
	if m != nil {
		return m.DomainProject
	}
	return ""
}

func (m *SyncMapping) GetOrgServiceID() string {
	if m != nil {
		return m.OrgServiceID
	}
	return ""
}

func (m *SyncMapping) GetOrgInstanceID() string {
	if m != nil {
		return m.OrgInstanceID
	}
	return ""
}

func (m *SyncMapping) GetCurServiceID() string {
	if m != nil {
		return m.CurServiceID
	}
	return ""
}

func (m *SyncMapping) GetCurInstanceID() string {
	if m != nil {
		return m.CurInstanceID
	}
	return ""
}

func init() {
	proto1.RegisterType((*PullRequest)(nil), "proto.PullRequest")
	proto1.RegisterType((*SyncService)(nil), "proto.SyncService")
	proto1.RegisterType((*SyncData)(nil), "proto.SyncData")
	proto1.RegisterType((*SyncMapping)(nil), "proto.SyncMapping")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Sync service

type SyncClient interface {
	Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*SyncData, error)
}

type syncClient struct {
	cc *grpc.ClientConn
}

func NewSyncClient(cc *grpc.ClientConn) SyncClient {
	return &syncClient{cc}
}

func (c *syncClient) Pull(ctx context.Context, in *PullRequest, opts ...grpc.CallOption) (*SyncData, error) {
	out := new(SyncData)
	err := grpc.Invoke(ctx, "/proto.Sync/Pull", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Sync service

type SyncServer interface {
	Pull(context.Context, *PullRequest) (*SyncData, error)
}

func RegisterSyncServer(s *grpc.Server, srv SyncServer) {
	s.RegisterService(&_Sync_serviceDesc, srv)
}

func _Sync_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sync/Pull",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncServer).Pull(ctx, req.(*PullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Sync_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Sync",
	HandlerType: (*SyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Pull",
			Handler:    _Sync_Pull_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "syncer.proto",
}

func init() { proto1.RegisterFile("syncer.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xff, 0xfc, 0x4d, 0x69, 0x7b, 0x53, 0x40, 0xba, 0x2c, 0x51, 0x59, 0xaa, 0x88, 0xa1,
	0x4b, 0x3b, 0x14, 0x31, 0xc0, 0xda, 0x2e, 0x1d, 0x0a, 0x55, 0x3a, 0x33, 0x18, 0x63, 0x55, 0x46,
	0xad, 0x1d, 0x6c, 0x07, 0xa9, 0x0f, 0xc3, 0xf3, 0xf0, 0x5a, 0xc8, 0x8e, 0x4d, 0x1d, 0x89, 0x81,
	0x29, 0xc9, 0xc9, 0xf1, 0x77, 0xef, 0x39, 0x32, 0x0c, 0xf5, 0x51, 0x50, 0xa6, 0x66, 0x95, 0x92,
	0x46, 0x62, 0xd7, 0x3d, 0x46, 0x17, 0x9a, 0xa9, 0x0f, 0x4e, 0x99, 0x6e, 0xe4, 0xe2, 0x19, 0xb2,
	0x4d, 0xbd, 0xdf, 0x97, 0xec, 0xbd, 0x66, 0xda, 0xe0, 0x18, 0x32, 0x6f, 0x78, 0x24, 0x07, 0x96,
	0x27, 0xe3, 0x64, 0x32, 0x28, 0x63, 0x09, 0x73, 0xe8, 0xc9, 0xca, 0x70, 0x29, 0x74, 0xfe, 0xdf,
	0xfd, 0x0d, 0x9f, 0x88, 0x90, 0x1a, 0x7e, 0x60, 0x79, 0xc7, 0xc9, 0xee, 0xbd, 0xf8, 0x4c, 0x20,
	0xdb, 0x1e, 0x05, 0xdd, 0x36, 0x04, 0xbc, 0x81, 0xf3, 0x57, 0x79, 0x20, 0x5c, 0x6c, 0x94, 0x7c,
	0x63, 0xd4, 0xf8, 0x09, 0x6d, 0x11, 0xa7, 0xd0, 0xf3, 0x23, 0xdd, 0x8c, 0x6c, 0x7e, 0xd5, 0x6c,
	0x3b, 0x5b, 0x73, 0xaa, 0xa4, 0x67, 0x95, 0xc1, 0x83, 0xf7, 0x30, 0xe0, 0x42, 0x1b, 0x22, 0x28,
	0xd3, 0x79, 0x67, 0xdc, 0x99, 0x64, 0xf3, 0xeb, 0x5f, 0x0e, 0xac, 0xbc, 0xa7, 0x3c, 0xb9, 0x8b,
	0x07, 0xe8, 0xdb, 0xf5, 0x96, 0xc4, 0x10, 0x9c, 0x41, 0x3f, 0x94, 0x93, 0x27, 0x8e, 0x82, 0x9e,
	0x12, 0x25, 0x28, 0x7f, 0x3c, 0xc5, 0x97, 0xcf, 0xb6, 0x26, 0x55, 0xc5, 0xc5, 0xee, 0x8f, 0xd9,
	0x0a, 0x18, 0x4a, 0xb5, 0x0b, 0x2b, 0x2d, 0x7d, 0x89, 0x2d, 0xcd, 0x92, 0x9e, 0xd4, 0x2e, 0xec,
	0xbb, 0x5a, 0xfa, 0x4a, 0xdb, 0xa2, 0x25, 0x2d, 0x6a, 0x75, 0x22, 0xa5, 0x0d, 0x29, 0xd6, 0x2c,
	0x69, 0x51, 0xab, 0x88, 0xd4, 0x6d, 0x48, 0x2d, 0x71, 0x7e, 0x07, 0xa9, 0x0d, 0x82, 0x53, 0x48,
	0xed, 0x65, 0xc0, 0x90, 0x3b, 0xba, 0x19, 0xa3, 0xcb, 0xa8, 0x0b, 0x5b, 0x57, 0xf1, 0xef, 0xe5,
	0xcc, 0x29, 0xb7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x05, 0x72, 0x53, 0x93, 0x69, 0x02, 0x00,
	0x00,
}
